name: Build and send mail
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get my repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: aliek.off
          password: Kalinochka123
          secure: true
          subject: Github Actions job result
          body: Держи
          from: Vladislav devOps
          to: mel04nax@gmail.com
          attachments: ./dist
