name: Linter
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get my repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get my repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build app for production
        run: npm run build
      - name: Send build prod version in email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://dockannes:Kalinochka123@smtp.gmail.com:465
          server_port: 465
          secure: true
          subject: Github Actions job result
          from: Vladislav devOps
          to: mel04nax@gmail.com
          attachments: ./dist