name: Linter
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint